name: Conventional commits (PR)

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

permissions:
  contents: read

jobs:
  conventional-commits:
    name: Validate PR title and commit messages

    permissions:
      pull-requests: read # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
    runs-on: [ubuntu-latest]

    steps:
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Configure which scopes are allowed.
        # scopes: |
        #   test-alpha
        #   deps
        # Configure that a scope must always be provided.
        requireScope: false

    - name: Validate PR commit messages
      uses: taskmedia/action-conventional-commits@ac561a9468c9c2454544d5b195532753e198e601 # v1.1.5
      with:
        types: "feat|fix|revert|chore|docs|test|ci"
