name: Conventional commits (PR)

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

permissions:
  contents: read

jobs:
  conventional-commits:
    name: Validate PR title and commit messages

    permissions:
      pull-requests: read # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
    runs-on: [ubuntu-latest]

    steps:
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f # v5.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Configure which scopes are allowed.
        # scopes: |
        #   test-alpha
        #   deps
        # Configure that a scope must always be provided.
        requireScope: false

    - name: Validate PR commit messages
      uses: taskmedia/action-conventional-commits@c456aecd4b015ea599c6a4dbb169559882267bc7 # v1.1.16
      with:
        types: "feat|fix|revert|chore|docs|test|ci"
