name: Chart Release
on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - uses: google-github-actions/release-please-action@v3
      with:
        release-type: node
        pull-request-title-pattern: "chore(release): ${component} ${version}"
        changelog-types: >
          [
            { "type": "feat", "section": "Features" },
            { "type": "fix", "section": "Bug Fixes" },
            { "type": "revert", "section": "Reverts" },
            { "type": "chore", "section": "Miscellaneous Chores" },
            { "type": "docs", "section": "Documentation" },
            { "type": "test", "section": "Tests", "hidden": "true" },
            { "type": "ci", "section": "Continuous Integration", "hidden": "true" }
          ]

