name: Chart Release
on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - uses: google-github-actions/release-please-action@v3
      id: rpa
      with:
        release-type: node
        pull-request-title-pattern: "chore(release): ${component} ${version}"
        changelog-types: >
          [
            { "type": "feat", "section": "Features" },
            { "type": "fix", "section": "Bug Fixes" },
            { "type": "revert", "section": "Reverts" },
            { "type": "chore", "section": "Miscellaneous Chores" },
            { "type": "docs", "section": "Documentation" },
            { "type": "test", "section": "Tests", "hidden": "true" },
            { "type": "ci", "section": "Continuous Integration", "hidden": "true" }
          ]

    - name: checkout releae please PR branch
      if: ${{ steps.rpa.outputs.pr }}
      shell: bash
      run: |
        RPA_PR_JSON='${{ steps.rpa.outputs.pr }}'
        headBranchName=$(echo $RPA_PR_JSON | tr -d '\n' | jq -r '.headBranchName')
        echo "checking out PR headBranchName: $headBranchName"
        git fetch
        git checkout $headBranchName

    - run: yarn install
      if: ${{ steps.rpa.outputs.pr }}

    - run: yarn lint
      if: ${{ steps.rpa.outputs.pr }}

    # - run: yarn test
    #   if: ${{ steps.release.outputs.release_created }}

    - run: yarn prepublish
      if: ${{ steps.rpa.outputs.pr }}

    - name: Commit and push to pull request
      if: ${{ steps.rpa.outputs.pr }}
      uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
      with:
        add_options: --force
        commit_message: |
          chore(build): build dist for release

          This is an automatic commit to release the binaries.

        file_pattern: 'dist/*'
